MAGIC_HEADER = b"TSET"
MAGIC_FOOTER = b"TEND"
MAGIC_DOC_BLOCK = b"DBLK"
MAGIC_VIEW = b"TVEW"
MAGIC_COLUMN_SECTION = b"TCOL"
MAGIC_AUDIT_LOG = b"TLOG"
MAGIC_SMT = b"TSMT"

VERSION_MAJOR = 0
VERSION_MINOR = 3
SUPPORTED_MINOR_VERSIONS = (1, 2, 3)

HEADER_SIZE = 4096
FOOTER_SIZE = 40

HASH_SIZE = 32
TRUNCATED_HASH_SIZE = 28

DEFAULT_BLOCK_TARGET_BYTES = 8 * 1024 * 1024
DEFAULT_TOKEN_CHUNK_SIZE = 65536
DEFAULT_SPARSE_INDEX_INTERVAL = 65536

ZSTD_LEVEL = 6
